SET NAMES utf8;

DROP DATABASE IF EXISTS openfoodfacts;

CREATE DATABASE openfoodfacts;


CREATE TABLE Products(
	id  VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL,
	url  VARCHAR(400) NOT NULL,
	stores VARCHAR(200),
	PRIMARY KEY(id)
)

CREATE TABLE Categories(
	id VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
)

CREATE TABLE Favorites(
	id INT UNSIGNED AUTO_INCREMENT,
	product_id INT UNSIGNED NOT NULL,
	PRIMARY KEY(id)
)